language: php
sudo: false
php:
  - '5.6'
  - '7.2'
before_install:
  # workaround for travis ipv6 timeout issue
  - sudo sh -c "echo 'precedence ::ffff:0:0/96 100' >> /etc/gai.conf"
  - composer config -g repo.packagist composer https://packagist.phpcomposer.com
  - composer install

script: composer phpcs && composer test
