<?php
/**
 * ShipmentItemPost
 *
 * PHP version 5
 *
 * @category Class
 * @package  TrackMage\Client\Swagger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trackmage Public API
 *
 * TrackMage API
 *
 * The version of the OpenAPI document: dev
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TrackMage\Client\Swagger\Model;

use \ArrayAccess;
use \TrackMage\Client\Swagger\ObjectSerializer;

/**
 * ShipmentItemPost Class Doc Comment
 *
 * @category Class
 * @package  TrackMage\Client\Swagger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class ShipmentItemPost implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'ShipmentItem-Post';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'shipment' => '\TrackMage\Client\Swagger\Model\ShipmentPost',
        'orderItem' => 'string',
        'qty' => 'int',
        'externalSourceSyncId' => 'string',
        'externalSourceIntegration' => 'string',
        'fulfillmentIntegration' => 'string',
        'fulfillmentSyncId' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'shipment' => null,
        'orderItem' => 'iri-reference',
        'qty' => null,
        'externalSourceSyncId' => null,
        'externalSourceIntegration' => 'iri-reference',
        'fulfillmentIntegration' => 'iri-reference',
        'fulfillmentSyncId' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shipment' => 'shipment',
        'orderItem' => 'orderItem',
        'qty' => 'qty',
        'externalSourceSyncId' => 'externalSourceSyncId',
        'externalSourceIntegration' => 'externalSourceIntegration',
        'fulfillmentIntegration' => 'fulfillmentIntegration',
        'fulfillmentSyncId' => 'fulfillmentSyncId'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shipment' => 'setShipment',
        'orderItem' => 'setOrderItem',
        'qty' => 'setQty',
        'externalSourceSyncId' => 'setExternalSourceSyncId',
        'externalSourceIntegration' => 'setExternalSourceIntegration',
        'fulfillmentIntegration' => 'setFulfillmentIntegration',
        'fulfillmentSyncId' => 'setFulfillmentSyncId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shipment' => 'getShipment',
        'orderItem' => 'getOrderItem',
        'qty' => 'getQty',
        'externalSourceSyncId' => 'getExternalSourceSyncId',
        'externalSourceIntegration' => 'getExternalSourceIntegration',
        'fulfillmentIntegration' => 'getFulfillmentIntegration',
        'fulfillmentSyncId' => 'getFulfillmentSyncId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipment'] = isset($data['shipment']) ? $data['shipment'] : null;
        $this->container['orderItem'] = isset($data['orderItem']) ? $data['orderItem'] : null;
        $this->container['qty'] = isset($data['qty']) ? $data['qty'] : null;
        $this->container['externalSourceSyncId'] = isset($data['externalSourceSyncId']) ? $data['externalSourceSyncId'] : null;
        $this->container['externalSourceIntegration'] = isset($data['externalSourceIntegration']) ? $data['externalSourceIntegration'] : null;
        $this->container['fulfillmentIntegration'] = isset($data['fulfillmentIntegration']) ? $data['fulfillmentIntegration'] : null;
        $this->container['fulfillmentSyncId'] = isset($data['fulfillmentSyncId']) ? $data['fulfillmentSyncId'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['shipment'] === null) {
            $invalidProperties[] = "'shipment' can't be null";
        }
        if ($this->container['orderItem'] === null) {
            $invalidProperties[] = "'orderItem' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipment
     *
     * @return \TrackMage\Client\Swagger\Model\ShipmentPost
     */
    public function getShipment()
    {
        return $this->container['shipment'];
    }

    /**
     * Sets shipment
     *
     * @param \TrackMage\Client\Swagger\Model\ShipmentPost $shipment shipment
     *
     * @return $this
     */
    public function setShipment($shipment)
    {
        $this->container['shipment'] = $shipment;

        return $this;
    }

    /**
     * Gets orderItem
     *
     * @return string
     */
    public function getOrderItem()
    {
        return $this->container['orderItem'];
    }

    /**
     * Sets orderItem
     *
     * @param string $orderItem orderItem
     *
     * @return $this
     */
    public function setOrderItem($orderItem)
    {
        $this->container['orderItem'] = $orderItem;

        return $this;
    }

    /**
     * Gets qty
     *
     * @return int|null
     */
    public function getQty()
    {
        return $this->container['qty'];
    }

    /**
     * Sets qty
     *
     * @param int|null $qty qty
     *
     * @return $this
     */
    public function setQty($qty)
    {
        $this->container['qty'] = $qty;

        return $this;
    }

    /**
     * Gets externalSourceSyncId
     *
     * @return string|null
     */
    public function getExternalSourceSyncId()
    {
        return $this->container['externalSourceSyncId'];
    }

    /**
     * Sets externalSourceSyncId
     *
     * @param string|null $externalSourceSyncId externalSourceSyncId
     *
     * @return $this
     */
    public function setExternalSourceSyncId($externalSourceSyncId)
    {
        $this->container['externalSourceSyncId'] = $externalSourceSyncId;

        return $this;
    }

    /**
     * Gets externalSourceIntegration
     *
     * @return string|null
     */
    public function getExternalSourceIntegration()
    {
        return $this->container['externalSourceIntegration'];
    }

    /**
     * Sets externalSourceIntegration
     *
     * @param string|null $externalSourceIntegration externalSourceIntegration
     *
     * @return $this
     */
    public function setExternalSourceIntegration($externalSourceIntegration)
    {
        $this->container['externalSourceIntegration'] = $externalSourceIntegration;

        return $this;
    }

    /**
     * Gets fulfillmentIntegration
     *
     * @return string|null
     */
    public function getFulfillmentIntegration()
    {
        return $this->container['fulfillmentIntegration'];
    }

    /**
     * Sets fulfillmentIntegration
     *
     * @param string|null $fulfillmentIntegration fulfillmentIntegration
     *
     * @return $this
     */
    public function setFulfillmentIntegration($fulfillmentIntegration)
    {
        $this->container['fulfillmentIntegration'] = $fulfillmentIntegration;

        return $this;
    }

    /**
     * Gets fulfillmentSyncId
     *
     * @return string|null
     */
    public function getFulfillmentSyncId()
    {
        return $this->container['fulfillmentSyncId'];
    }

    /**
     * Sets fulfillmentSyncId
     *
     * @param string|null $fulfillmentSyncId fulfillmentSyncId
     *
     * @return $this
     */
    public function setFulfillmentSyncId($fulfillmentSyncId)
    {
        $this->container['fulfillmentSyncId'] = $fulfillmentSyncId;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


