<?php
/**
 * WorkspaceGet
 *
 * PHP version 5
 *
 * @category Class
 * @package  TrackMage\Client\Swagger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Trackmage Public API
 *
 * TrackMage API
 *
 * The version of the OpenAPI document: dev
 * 
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.3.1
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace TrackMage\Client\Swagger\Model;

use \ArrayAccess;
use \TrackMage\Client\Swagger\ObjectSerializer;

/**
 * WorkspaceGet Class Doc Comment
 *
 * @category Class
 * @package  TrackMage\Client\Swagger
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class WorkspaceGet implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $openAPIModelName = 'Workspace-Get';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPITypes = [
        'team' => '\TrackMage\Client\Swagger\Model\TeamGet',
        'title' => 'string',
        'defaultTrackingPage' => 'string',
        'shipmentsCount' => 'int',
        'workflowsCount' => 'int',
        'workflowsOrder' => 'string[]',
        'logo' => '\TrackMage\Client\Swagger\Model\MediaGet',
        'emailSettings' => 'object',
        'id' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $openAPIFormats = [
        'team' => null,
        'title' => null,
        'defaultTrackingPage' => 'iri-reference',
        'shipmentsCount' => null,
        'workflowsCount' => null,
        'workflowsOrder' => null,
        'logo' => null,
        'emailSettings' => null,
        'id' => 'uuid'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPITypes()
    {
        return self::$openAPITypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function openAPIFormats()
    {
        return self::$openAPIFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'team' => 'team',
        'title' => 'title',
        'defaultTrackingPage' => 'defaultTrackingPage',
        'shipmentsCount' => 'shipmentsCount',
        'workflowsCount' => 'workflowsCount',
        'workflowsOrder' => 'workflowsOrder',
        'logo' => 'logo',
        'emailSettings' => 'emailSettings',
        'id' => 'id'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'team' => 'setTeam',
        'title' => 'setTitle',
        'defaultTrackingPage' => 'setDefaultTrackingPage',
        'shipmentsCount' => 'setShipmentsCount',
        'workflowsCount' => 'setWorkflowsCount',
        'workflowsOrder' => 'setWorkflowsOrder',
        'logo' => 'setLogo',
        'emailSettings' => 'setEmailSettings',
        'id' => 'setId'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'team' => 'getTeam',
        'title' => 'getTitle',
        'defaultTrackingPage' => 'getDefaultTrackingPage',
        'shipmentsCount' => 'getShipmentsCount',
        'workflowsCount' => 'getWorkflowsCount',
        'workflowsOrder' => 'getWorkflowsOrder',
        'logo' => 'getLogo',
        'emailSettings' => 'getEmailSettings',
        'id' => 'getId'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$openAPIModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['team'] = isset($data['team']) ? $data['team'] : null;
        $this->container['title'] = isset($data['title']) ? $data['title'] : null;
        $this->container['defaultTrackingPage'] = isset($data['defaultTrackingPage']) ? $data['defaultTrackingPage'] : null;
        $this->container['shipmentsCount'] = isset($data['shipmentsCount']) ? $data['shipmentsCount'] : null;
        $this->container['workflowsCount'] = isset($data['workflowsCount']) ? $data['workflowsCount'] : null;
        $this->container['workflowsOrder'] = isset($data['workflowsOrder']) ? $data['workflowsOrder'] : null;
        $this->container['logo'] = isset($data['logo']) ? $data['logo'] : null;
        $this->container['emailSettings'] = isset($data['emailSettings']) ? $data['emailSettings'] : null;
        $this->container['id'] = isset($data['id']) ? $data['id'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if ($this->container['team'] === null) {
            $invalidProperties[] = "'team' can't be null";
        }
        if ($this->container['title'] === null) {
            $invalidProperties[] = "'title' can't be null";
        }
        if ($this->container['defaultTrackingPage'] === null) {
            $invalidProperties[] = "'defaultTrackingPage' can't be null";
        }
        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets team
     *
     * @return \TrackMage\Client\Swagger\Model\TeamGet
     */
    public function getTeam()
    {
        return $this->container['team'];
    }

    /**
     * Sets team
     *
     * @param \TrackMage\Client\Swagger\Model\TeamGet $team team
     *
     * @return $this
     */
    public function setTeam($team)
    {
        $this->container['team'] = $team;

        return $this;
    }

    /**
     * Gets title
     *
     * @return string
     */
    public function getTitle()
    {
        return $this->container['title'];
    }

    /**
     * Sets title
     *
     * @param string $title title
     *
     * @return $this
     */
    public function setTitle($title)
    {
        $this->container['title'] = $title;

        return $this;
    }

    /**
     * Gets defaultTrackingPage
     *
     * @return string
     */
    public function getDefaultTrackingPage()
    {
        return $this->container['defaultTrackingPage'];
    }

    /**
     * Sets defaultTrackingPage
     *
     * @param string $defaultTrackingPage defaultTrackingPage
     *
     * @return $this
     */
    public function setDefaultTrackingPage($defaultTrackingPage)
    {
        $this->container['defaultTrackingPage'] = $defaultTrackingPage;

        return $this;
    }

    /**
     * Gets shipmentsCount
     *
     * @return int|null
     */
    public function getShipmentsCount()
    {
        return $this->container['shipmentsCount'];
    }

    /**
     * Sets shipmentsCount
     *
     * @param int|null $shipmentsCount shipmentsCount
     *
     * @return $this
     */
    public function setShipmentsCount($shipmentsCount)
    {
        $this->container['shipmentsCount'] = $shipmentsCount;

        return $this;
    }

    /**
     * Gets workflowsCount
     *
     * @return int|null
     */
    public function getWorkflowsCount()
    {
        return $this->container['workflowsCount'];
    }

    /**
     * Sets workflowsCount
     *
     * @param int|null $workflowsCount workflowsCount
     *
     * @return $this
     */
    public function setWorkflowsCount($workflowsCount)
    {
        $this->container['workflowsCount'] = $workflowsCount;

        return $this;
    }

    /**
     * Gets workflowsOrder
     *
     * @return string[]|null
     */
    public function getWorkflowsOrder()
    {
        return $this->container['workflowsOrder'];
    }

    /**
     * Sets workflowsOrder
     *
     * @param string[]|null $workflowsOrder workflowsOrder
     *
     * @return $this
     */
    public function setWorkflowsOrder($workflowsOrder)
    {
        $this->container['workflowsOrder'] = $workflowsOrder;

        return $this;
    }

    /**
     * Gets logo
     *
     * @return \TrackMage\Client\Swagger\Model\MediaGet|null
     */
    public function getLogo()
    {
        return $this->container['logo'];
    }

    /**
     * Sets logo
     *
     * @param \TrackMage\Client\Swagger\Model\MediaGet|null $logo logo
     *
     * @return $this
     */
    public function setLogo($logo)
    {
        $this->container['logo'] = $logo;

        return $this;
    }

    /**
     * Gets emailSettings
     *
     * @return object|null
     */
    public function getEmailSettings()
    {
        return $this->container['emailSettings'];
    }

    /**
     * Sets emailSettings
     *
     * @param object|null $emailSettings emailSettings
     *
     * @return $this
     */
    public function setEmailSettings($emailSettings)
    {
        $this->container['emailSettings'] = $emailSettings;

        return $this;
    }

    /**
     * Gets id
     *
     * @return string|null
     */
    public function getId()
    {
        return $this->container['id'];
    }

    /**
     * Sets id
     *
     * @param string|null $id id
     *
     * @return $this
     */
    public function setId($id)
    {
        $this->container['id'] = $id;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        return json_encode(
            ObjectSerializer::sanitizeForSerialization($this),
            JSON_PRETTY_PRINT
        );
    }

    /**
     * Gets a header-safe presentation of the object
     *
     * @return string
     */
    public function toHeaderValue()
    {
        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


