name: Code_Checks

on:
  pull_request: null
  push:
    branches:
      - master

jobs:
  tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php: ['7.2', '7.4']

    name: PHP ${{ matrix.php }} tests
    steps:
      # basically git clone
      - uses: actions/checkout@v2

      # use PHP of specific version
      - uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          coverage: none # disable xdebug, pcov

      # if we 2 steps like this, we can better see if composer failed or tests
      - run: composer install --no-progress
      - run: vendor/bin/phpstan analyse -c phpstan.neon
      - run: vendor/bin/phpstan analyse -c phpstan-tests.neon
      - run: composer test
